In [1]:
import tensorflow as tf
from tensorflow import keras as ks
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [2]:
config = ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.7
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)

In [3]:
# session.close()

In [5]:
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True,
                                      rotation_range = 20
                                 )
training_set = train_datagen.flow_from_directory('train',
                                                 target_size = (100, 100),
                                                 batch_size = 32,
                                                 class_mode = "categorical")

Found 1951 images belonging to 4 classes.


In [6]:
test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory('test',
                                            target_size = (100, 100),
                                                 batch_size = 32,
                                                 class_mode = "categorical")

Found 106 images belonging to 4 classes.


In [40]:
# inp = tf.keras.layers.Input(shape =(100,100,3))
# inp1 = tf.keras.layers.Conv2D(32,padding='same',kernel_size=(3,3),kernel_initializer=tf.keras.initializers.he_normal())(inp1)
# inp1 = tf.keras.layers.BatchNormalization()(inp1)
# inp1 = tf.keras.layers.Activation('relu')(inp1)
# inp1 = tf.keras.layers.Conv2D(32,padding='same',kernel_size=3,kernel_initializer=tf.keras.initializers.he_normal())(inp1)
# inp1 = tf.keras.layers.BatchNormalization()(inp1)
# inp1 = tf.keras.layers.Activation('relu')(inp1)
# inp1 = tf.keras.layers.MaxPooling2D()(inp1)

# inp1 = tf.keras.layers.Conv2D(64,padding='same',kernel_size=3,kernel_initializer=tf.keras.initializers.he_normal())(inp1)
# inp1 = tf.keras.layers.BatchNormalization()(inp1)
# inp1 = tf.keras.layers.Activation('relu')(inp1)
# inp1 = tf.keras.layers.Conv2D(64,padding='same',kernel_size=3,kernel_initializer=tf.keras.initializers.he_normal())(inp1)
# inp1 = tf.keras.layers.BatchNormalization()(inp1)
# inp1 = tf.keras.layers.Activation('relu')(inp1)
# inp1 = tf.keras.layers.MaxPooling2D()(inp1)

# # inp = ks.layers.GlobalAveragePooling2D()(inp)
# inp1 = tf.keras.layers.Flatten()(inp1)
# inp1 = tf.keras.layers.Dense(256, activation='relu',kernel_initializer=tf.keras.initializers.he_normal())(inp1)
# inp1 = tf.keras.layers.Dropout(0.5)(inp1)
# inp1 = tf.keras.layers.Dense(80, activation='relu',kernel_initializer=tf.keras.initializers.he_normal())(inp1)
# inp1 = tf.keras.layers.Dropout(0.5)(inp1)
# inp1 = tf.keras.layers.Dense(4,activation='softmax',kernel_initializer="glorot_uniform")(inp1)
# model = tf.keras.models.Model(inputs =inp,outputs=inp1)

In [49]:
# Initialising the CNN
cnn = tf.keras.models.Sequential()

# Step 1 - Convolution
cnn.add(tf.keras.layers.Conv2D(filters=32,padding="same",kernel_size=3,kernel_initializer=tf.keras.initializers.he_normal() 
                              , input_shape=[100, 100, 3]))
cnn.add(tf.keras.layers.BatchNormalization())
cnn.add(tf.keras.layers.Activation('relu'))

cnn.add(tf.keras.layers.Conv2D(filters=32,padding="same",kernel_size=3,kernel_initializer=tf.keras.initializers.he_normal() ))
cnn.add(tf.keras.layers.BatchNormalization())
cnn.add(tf.keras.layers.Activation('relu'))
cnn.add(tf.keras.layers.MaxPool2D())

cnn.add(tf.keras.layers.Conv2D(filters=64,padding="same",kernel_size=3,kernel_initializer=tf.keras.initializers.he_normal()))
cnn.add(tf.keras.layers.BatchNormalization())
cnn.add(tf.keras.layers.Activation('relu'))

cnn.add(tf.keras.layers.Conv2D(filters=64,padding="same",kernel_size=3,kernel_initializer=tf.keras.initializers.he_normal() ))
cnn.add(tf.keras.layers.BatchNormalization())
cnn.add(tf.keras.layers.Activation('relu'))
cnn.add(tf.keras.layers.MaxPool2D())

cnn.add(tf.keras.layers.Conv2D(filters=128,padding="same",kernel_size=3,kernel_initializer=tf.keras.initializers.he_normal()))
cnn.add(tf.keras.layers.BatchNormalization())
cnn.add(tf.keras.layers.Activation('relu'))

cnn.add(tf.keras.layers.Conv2D(filters=128,padding="same",kernel_size=3,kernel_initializer=tf.keras.initializers.he_normal() ))
cnn.add(tf.keras.layers.BatchNormalization())
cnn.add(tf.keras.layers.Activation('relu'))
cnn.add(tf.keras.layers.MaxPool2D())
cnn.add(tf.keras.layers.GlobalAveragePooling2D())
# # Adding a second convolutional layer
# cnn.add(tf.keras.layers.Conv2D(filters=32,padding='same',kernel_size=3, activation='relu'))
# cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

# # Step 3 - Flattening
# cnn.add(tf.keras.layers.Flatten())

# # Step 4 - Full Connection
# cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))

# Step 5 - Output Layer
cnn.add(tf.keras.layers.Dense(units=4, activation='softmax',kernel_initializer="glorot_uniform"))

In [50]:
cnn.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_105 (Conv2D)          (None, 100, 100, 32)      896       
_________________________________________________________________
batch_normalization_96 (Batc (None, 100, 100, 32)      128       
_________________________________________________________________
activation_96 (Activation)   (None, 100, 100, 32)      0         
_________________________________________________________________
conv2d_106 (Conv2D)          (None, 100, 100, 32)      9248      
_________________________________________________________________
batch_normalization_97 (Batc (None, 100, 100, 32)      128       
_________________________________________________________________
activation_97 (Activation)   (None, 100, 100, 32)      0         
_________________________________________________________________
max_pooling2d_49 (MaxPooling (None, 50, 50, 32)       

In [51]:
cnn.compile(optimizer = tf.keras.optimizers.Adam(), loss = tf.keras.losses.CategoricalCrossentropy(), metrics = ['accuracy'])

In [52]:
# Early_Stop = tf.keras.callbacks.EarlyStopping(patience=8,restore_best_weights=True)
# Check_Point = tf.keras.callbacks.ModelCheckpoint('My_Model.h5', save_best_only=True)
EarlyStopping = tf.keras.callbacks.EarlyStopping(patience=8,restore_best_weights=True)
Check_Point = tf.keras.callbacks.ModelCheckpoint('My_Model.h5', save_best_weights=True)
cnn.fit(x = training_set, validation_data = test_set, epochs = 100,callbacks =[EarlyStopping,Check_Point])

  ...
    to  
  ['...']
  ...
    to  
  ['...']
Train for 61 steps, validate for 4 steps
Epoch 1/100
61/61 [==============================] - 28s 455ms/step - loss: 0.7206 - accuracy: 0.7186 - val_loss: 10.8909 - val_accuracy: 0.2358
Epoch 2/100
61/61 [==============================] - 21s 342ms/step - loss: 0.4643 - accuracy: 0.8165 - val_loss: 3.6615 - val_accuracy: 0.3962
Epoch 3/100
61/61 [==============================] - 16s 257ms/step - loss: 0.3637 - accuracy: 0.8580 - val_loss: 1.0611 - val_accuracy: 0.6415
Epoch 4/100
61/61 [==============================] - 16s 257ms/step - loss: 0.3048 - accuracy: 0.8919 - val_loss: 1.2940 - val_accuracy: 0.6415
Epoch 5/100
61/61 [==============================] - 16s 257ms/step - loss: 0.2679 - accuracy: 0.9001 - val_loss: 0.4682 - val_accuracy: 0.8208
Epoch 6/100
61/61 [==============================] - 16s 257ms/step - loss: 0.2496 - accuracy: 0.9113 - val_loss: 0.3720 - val_accuracy: 0.8302
Epoch 7/100
61/61 [=========================

In [60]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow.keras.models import load_model

In [62]:
# pd.DataFrame(cnn.history).plot(figsize=(8, 5))
# plt.grid(True)
# plt.gca().set_ylim(0, 1)
# plt.show()

In [55]:
model = load_model('My_Model.h5')
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_105 (Conv2D)          (None, 100, 100, 32)      896       
_________________________________________________________________
batch_normalization_96 (Batc (None, 100, 100, 32)      128       
_________________________________________________________________
activation_96 (Activation)   (None, 100, 100, 32)      0         
_________________________________________________________________
conv2d_106 (Conv2D)          (None, 100, 100, 32)      9248      
_________________________________________________________________
batch_normalization_97 (Batc (None, 100, 100, 32)      128       
_________________________________________________________________
activation_97 (Activation)   (None, 100, 100, 32)      0         
_________________________________________________________________
max_pooling2d_49 (MaxPooling (None, 50, 50, 32)       

In [56]:
import numpy as np
from tensorflow.keras.preprocessing import image
test_image = image.load_img('test/diseased cotton leaf/dis_leaf (175)_iaip.jpg', target_size = (100,100))
test_image = image.img_to_array(test_image)
test_image=test_image/255
test_image = np.expand_dims(test_image, axis = 0)
result = model.predict(test_image)
result

array([[9.9998164e-01, 7.5701823e-06, 7.3478391e-06, 3.3534000e-06]],
      dtype=float32)

In [57]:
class1=model.predict_classes(test_image)
class1


array([0], dtype=int64)

In [65]:
t = test_set.class_indices

In [73]:
t


{'diseased cotton leaf': 0,
 'diseased cotton plant': 1,
 'fresh cotton leaf': 2,
 'fresh cotton plant': 3}

In [78]:
#  test_set.classes

In [76]:
label_map = (test_set.class_indices)
label_map = dict((v,k) for k,v in label_map.items())
pred = [label_map[k] for k in class1]

In [77]:
pred

['diseased cotton leaf']

In [79]:
model.predict_proba(test_image)

array([[9.9998164e-01, 7.5701823e-06, 7.3478391e-06, 3.3534000e-06]],
      dtype=float32)